### ISSUE TITLE
Update Android clients

### ISSUE THREAD

**Issue by Monsterovich** [TokTok/website#152]
- Antox is outdated and no longer maintained.
- Add [Protox](https://gitlab.com/Monsterovich/protox), ~~[Trifa](https://github.com/zoff99/ToxAndroidRefImpl)~~ and Atox (if it's ready) to the list.

**Comment by zoff99** [comment]
@Monsterovich i think you actually meant this repo:
https://github.com/Tox/tox.chat

**Comment by Monsterovich** [comment]
> @Monsterovich i think you actually meant this repo:
> https://github.com/Tox/tox.chat

Yes, but this site has such list too. https://toktok.ltd/integrations.html

**Comment by zoff99** [comment]
TRIfA is already on that list.
you can make a PR to add Protox and aTox.
