### ISSUE TITLE
Add "reload" button or link to pulls page

### ISSUE THREAD

**Issue by iphydf** [TokTok/website#24]
Don't erase the table before the new one is in place.

**Comment by cebe** [comment]
to reload parts of the page?

**Comment by iphydf** [comment]
To reload the table that is generated by JS.

**Comment by cebe** [comment]
to reload the whole table you could just refresh the page. what does the button do differnet?

**Comment by iphydf** [comment]
If I reload the page and I'm looking at the bottom of the list, I end up being at the top and need to scroll down again.
