### ISSUE TITLE
Fold `Pull Requests` page into `Repositories` page

### ISSUE THREAD

**Issue by Zer0-One** [TokTok/website#62]
The `Pull Requests` page should be removed. The `PRs` link for each repository on the `Repositories` page should load a page with the appropriate PR table (as currently displayed on the `Pull Requests` page) on it.

**Comment by iphydf** [comment]
We can add those separate pages, but I really like to have the overview of all PRs across repos. For a per-repo PR table, you can also use github. The point of this table was to have a whole-org PR overview.

**Comment by Zer0-One** [comment]
You could also have a "meta" `All Repositories` repo listed on the page that would bring up the whole-org overview.
